name: third_party_archive
description: "PathOfExile third party archive"
publish_to: "none"

version: 1.0.0+5

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  horoli_package:
    git:
      url: "https://github.com/Horoli/horoli_package.git"
      ref: "master"
  flutter_fortune_wheel: ^1.3.1
  http: ^1.2.1
  get: ^4.6.6
  device_info_plus: ^10.0.1
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  simple_icons: ^10.1.3
  timezone: ^0.9.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
